language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4.1.gemfile
dist: trusty
sudo: false
cache:
  bundler: true
before_install:
  - gem install bundler
before_script:
  - cp spec/dummy/config/database.yml.ci spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake app:db:create app:db:migrate
script:
  - bundle exec rspec spec
after_script:
  - RAILS_ENV=test bundle exec rake app:db:drop
env:
  global:
    - DEVISE_SECRET_KEY=foo
