language: ruby
rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.3
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
dist: trusty
sudo: false
cache:
  bundler: true
before_install:
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp spec/dummy/config/database.yml.ci spec/dummy/config/database.yml
  - psql -c 'create database g5_authenticatable_test;' -U postgres
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $EXIT_CODE
  - RAILS_ENV=test bundle exec rake app:db:drop
env:
  global:
    - DEVISE_SECRET_KEY=foo
