language: ruby
rvm:
  - 2.3.4
gemfiles:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
before_install:
  - gem install bundler
before_script:
  - cp spec/dummy/config/database.yml.ci spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake app:db:create app:db:migrate
script:
  - bundle exec rspec spec
after_script:
  - RAILS_ENV=test bundle exec rake app:db:drop
env:
  global:
    - DEVISE_SECRET_KEY=foo
