development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development
  pool: 5
  username: vagrant

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test
  pool: 5
  username: vagrant
